import { Writer } from '@/types/admin-types'
import { TEpisode, TGetEpisodeResponse } from '@/types/episode-type'

export const MOCK_WRITERS: Writer[] = [
	{
		id: 1,
		name: 'Hannah Smith',
		cmsThroughputDay: 5.27,
		cmsThroughputMonth: 91.5,
		writingDaysPerWeek: 3.1,
		totalScripts: 37,
		vacationDays: 2,
		totalBriefs: 295,
		totalHours: 142.5,
		isWorking: true,
	},
	{
		id: 2,
		name: 'Michael Johnson',
		cmsThroughputDay: 4.82,
		cmsThroughputMonth: 85.96,
		writingDaysPerWeek: 4.5,
		totalScripts: 40,
		vacationDays: 0,
		totalBriefs: 320,
		totalHours: 160,
		isWorking: true,
	},
	{
		id: 3,
		name: 'Sophia Williams',
		cmsThroughputDay: 6.1,
		cmsThroughputMonth: 110.25,
		writingDaysPerWeek: 5.0,
		totalScripts: 55,
		vacationDays: 1,
		totalBriefs: 350,
		totalHours: 170.8,
		isWorking: true,
	},
	{
		id: 4,
		name: 'Daniel Brown',
		cmsThroughputDay: 3.78,
		cmsThroughputMonth: 67.95,
		writingDaysPerWeek: 2.8,
		totalScripts: 25,
		vacationDays: 3,
		totalBriefs: 200,
		totalHours: 120.5,
		isWorking: false,
	},
	{
		id: 5,
		name: 'Emily Davis',
		cmsThroughputDay: 5.95,
		cmsThroughputMonth: 105.23,
		writingDaysPerWeek: 4.2,
		totalScripts: 48,
		vacationDays: 0,
		totalBriefs: 310,
		totalHours: 150.2,
		isWorking: true,
	},
	{
		id: 6,
		name: 'Ethan Wilson',
		cmsThroughputDay: 4.33,
		cmsThroughputMonth: 76.82,
		writingDaysPerWeek: 3.7,
		totalScripts: 32,
		vacationDays: 1,
		totalBriefs: 280,
		totalHours: 135.7,
		isWorking: true,
	},
	{
		id: 7,
		name: 'Olivia Miller',
		cmsThroughputDay: 6.45,
		cmsThroughputMonth: 115.33,
		writingDaysPerWeek: 5.0,
		totalScripts: 60,
		vacationDays: 0,
		totalBriefs: 400,
		totalHours: 180.5,
		isWorking: true,
	},
	{
		id: 8,
		name: 'James Moore',
		cmsThroughputDay: 3.91,
		cmsThroughputMonth: 68.47,
		writingDaysPerWeek: 3.2,
		totalScripts: 28,
		vacationDays: 4,
		totalBriefs: 220,
		totalHours: 128.3,
		isWorking: false,
	},
]

export const MOCK_FREQUENT_PROMPTS = [
	'Analysiere die dramaturgischen Beats dieser Episode und zeige auf, wo die dramatische Spannung nachlässt oder gesteigert werden sollte.',
	'Überprüfe die Dialogszenen und mache Vorschläge zu “character-revealing inner thoughts, more theatrical exchanges, and heightened emotional stakes".',
	'Identifiziere Momente, in denen Konflikte zwischen den Charakteren intensiviert werden könnten, und schlage Möglichkeiten vor, ihre Dynamik dramatischer zu gestalten, ohne die Kernhandlung zu ändern.',
	'Zeichne die emotionale Entwicklung des Protagonisten in dieser Episode nach und verstärke seine Reaktionen, wobei der Fokus auf äußeren Hindernissen statt auf inneren Schwächen liegt.',
	'Überprüfe den Anfang/das Ende dieser Episode und schlage Möglichkeiten vor, einen spannenderen Hook oder Cliffhanger zu schaffen, der sofort Spannung aufbaut.',
	'Umzuschreibender Absatz:\n[INSERT PARAGRAPH]\n\n###\nBitte schreibe den obigen Absatz um, ergänze mehr farbenfrohe Beschreibungen hinzu und behalte dabei das Tempo bei. Füge während an den entsprechenden Momenten Hinweise für Musik und Soundeffekte ein – aber auf Englisch in diesem Format: SFX: MUSIC: \n\nRewrite Guidelines: \n- direkte Rede immer in Du-Form und jede Figur mit ihrer eigenen Umgangssprache \n- schreibe im Aktiv \n- verbessere die Lesbarkeit des Textes durch gute Grammatik - vermeide Partizipien.',
	'Schreibe eine neue Szene, in der der Protagonist eine wichtige Entscheidung trifft, die seine Charakterentwicklung widerspiegelt und zukünftige Konflikte vorbereitet.',
	'Erstelle eine Übersicht der Nebenfiguren in dieser Episode und schlage vor, wie ihre Rollen in den Hauptkonflikt eingebunden werden könnten.',
	'Analysiere die Spannungsbögen in den zentralen Szenen und schlage Alternativen vor, um den Aufbau und die Auflösung stärker zu gestalten.',
	'Ergänze den Dialog zwischen [CHARACTER 1] und [CHARACTER 2] mit stärkeren Emotionen und subtileren Subtexten.',
]

export const MOCK_SUCCESSFUL_PROMPTS = [
	'Überprüfe die Dialogszenen und mache Vorschläge zu “character-revealing inner thoughts, more theatrical exchanges, and heightened emotional stakes".',
	'Umzuschreibender Absatz:\n[INSERT PARAGRAPH]\n\n###\nBitte schreibe den obigen Absatz um, ergänze mehr farbenfrohe Beschreibungen hinzu und behalte dabei das Tempo bei. Füge während an den entsprechenden Momenten Hinweise für Musik und Soundeffekte ein – aber auf Englisch in diesem Format: SFX: MUSIC: \n\nRewrite Guidelines: \n- direkte Rede immer in Du-Form und jede Figur mit ihrer eigenen Umgangssprache \n- schreibe im Aktiv \n- verbessere die Lesbarkeit des Textes durch gute Grammatik - vermeide Partizipien.',
	'Zeichne die emotionale Entwicklung des Protagonisten in dieser Episode nach und verstärke seine Reaktionen, wobei der Fokus auf äußeren Hindernissen statt auf inneren Schwächen liegt.',
	'Analysiere die Spannungsbögen in den zentralen Szenen und schlage Alternativen vor, um den Aufbau und die Auflösung stärker zu gestalten.',
	'Überprüfe den Anfang/das Ende dieser Episode und schlage Möglichkeiten vor, einen spannenderen Hook oder Cliffhanger zu schaffen, der sofort Spannung aufbaut.',
	'Schreibe eine neue Szene, in der der Protagonist eine wichtige Entscheidung trifft, die seine Charakterentwicklung widerspiegelt und zukünftige Konflikte vorbereitet.',
	'Ergänze den Dialog zwischen [CHARACTER 1] und [CHARACTER 2] mit stärkeren Emotionen und subtileren Subtexten.',
	'Erstelle eine Übersicht der Nebenfiguren in dieser Episode und schlage vor, wie ihre Rollen in den Hauptkonflikt eingebunden werden könnten.',
	'Analysiere die dramaturgischen Beats dieser Episode und zeige auf, wo die dramatische Spannung nachlässt oder gesteigert werden sollte.',
	'Identifiziere Momente, in denen Konflikte zwischen den Charakteren intensiviert werden könnten, und schlage Möglichkeiten vor, ihre Dynamik dramatischer zu gestalten, ohne die Kernhandlung zu ändern.',
]

export const MOCK_RATIO_STORY = [
	'My Vampire System',
	'Insta Millionaire',
	'Test Project',
	'The Return',
	"The Duke's Masked Bride",
	"The Billionaire's Accidental Bride",
	'Saving Nora',
	'Rekindled Heartache',
]

export const MOCK_CHAPTER: TEpisode = {
	chapter_title: 'The Beginning of Everything',
	comments: 'This chapter introduces the main character and sets the tone.',
	context: 'Set in a dystopian future where AI governs society.',
	create_time: '2025-04-17T10:00:00Z',
	file_url: 'https://example.com/files/episode1.txt',
	id: 1,
	is_deleted: false,
	latest_version: 3,
	original_seq_number: 1,
	parent: null,
	project: 101,
	props: {
		comments: [],
		creation_timestamp: 1713342000,
		llm_memories: {
			summary: 'Introduces the protagonist and dystopian world setup.',
			beatsheet: '',
			context: '',
			loglines: '',
		},
		merged_chapter_ids: [],
		notes: [],
		original_chapters: [
			{
				chapter_title: 'Old Chapter 1',
				comments: null,
				context: null,
				create_time: '2024-12-01T08:00:00Z',
				file_url: 'https://example.com/files/old1.txt',
				id: 99,
				is_deleted: false,
				latest_version: 1,
				original_seq_number: 1,
				parent: null,
				project: 101,
				seq_number: 1,
				status: 'BASE',
				translation_url: null,
				type: 'draft',
				update_time: '2024-12-01T08:30:00Z',
				word_count: 1100,
			},
		],
	},
	seq_number: 1,
	status: 'BASE',
	translation_url: 'https://example.com/files/episode1_fr.txt',
	type: 'main',
	update_time: '2025-04-17T12:00:00Z',
	word_count: 2500,
	writer: 200,
}

export const MOCK_EPISODE: TGetEpisodeResponse = {
	chapter: MOCK_CHAPTER,
	next_parent_id: null,
	previous_parent_id: null,
	text: 'Dies ist der Text der Episode.',
	translation_text: 'This is the text of the episode.',
}
